




ansible_device_vendor: cisco
ansible_device_os: ios


ansible_ssh_pass: P@ssw0rd
ansible_become_pass: P@ssw0rd



ansible_connection: network_cli
ansible_network_os: ios
ansible_user: admin
#ansible_ssh_pass: !vault...
ansible_become: yes
ansible_become_method: enable
#ansible_become_pass: !vault...
#ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q bastion01"'
