---
- name: configure the login banner
  become: yes
  ios_banner:
    banner: login
    text: |
     @@@@@@@@@@@@@@@@@@@@@@@     
     @ Estas accediendo al @
     @ LABORATORIO DE      @
     @    NACHO             
    state: present

    #- name: remove the motd banner
    #  ios_banner:
    #    banner: motd
    #    state: absent

    #- name: Configure banner from file
    #  ios_banner:
    #    banner:  motd
    #    text: "{{ lookup('file', './config_partial/raw_banner.cfg') }}"
    #    state: present
